# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '02_hw_autoLayout' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 02_hw_autoLayout

pod 'Alamofire', '~> 4.8.2'

pod 'CHIPageControl', '~> 0.1.3'
pod 'CHIPageControl/Aji'
pod 'CHIPageControl/Aleppo'
pod 'CHIPageControl/Chimayo'
pod 'CHIPageControl/Fresno'
pod 'CHIPageControl/Jalapeno'
pod 'CHIPageControl/Jaloro'
pod 'CHIPageControl/Paprika'
pod 'CHIPageControl/Puya'

end
